
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: May 23 2025 23:34:21

// Verification Directory fv/synth_wrapper 

module DFF(in, clk, rst_n, out);
  input [3:0] in;
  input clk, rst_n;
  output [3:0] out;
  wire [3:0] in;
  wire clk, rst_n;
  wire [3:0] out;
  wire n_0;
  sky130_fd_sc_hd__dfrtp_1 \out_reg[2] (.RESET_B (rst_n), .CLK (clk),
       .D (in[2]), .Q (out[2]));
  sky130_fd_sc_hd__dfrtp_2 \out_reg[0] (.RESET_B (rst_n), .CLK (clk),
       .D (n_0), .Q (out[0]));
  sky130_fd_sc_hd__dfrtp_1 \out_reg[3] (.RESET_B (rst_n), .CLK (clk),
       .D (in[3]), .Q (out[3]));
  sky130_fd_sc_hd__dfrtp_1 \out_reg[1] (.RESET_B (rst_n), .CLK (clk),
       .D (in[1]), .Q (out[1]));
  sky130_fd_sc_hd__inv_1 g12(.A (out[0]), .Y (n_0));
endmodule

module counter(clk, rst_n, sel, out);
  input clk, rst_n, sel;
  output [3:0] out;
  wire clk, rst_n, sel;
  wire [3:0] out;
  wire [3:0] next_val;
  wire n_0, n_1, n_2, n_3, n_4, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12;
  DFF ff_inst(.in ({next_val[3:1], 1'b0}), .clk (clk), .rst_n (rst_n),
       .out (out));
  sky130_fd_sc_hd__xnor2_1 g145(.A (out[3]), .B (n_11), .Y
       (next_val[3]));
  sky130_fd_sc_hd__xnor2_1 g146(.A (out[2]), .B (n_12), .Y
       (next_val[2]));
  sky130_fd_sc_hd__o211ai_2 g147(.A1 (n_2), .A2 (sel), .B1 (n_6), .C1
       (n_10), .Y (n_12));
  sky130_fd_sc_hd__xor2_1 g148(.A (sel), .B (n_10), .X (next_val[1]));
  sky130_fd_sc_hd__nand4_2 g149(.A (n_10), .B (n_8), .C (n_7), .D
       (n_6), .Y (n_11));
  sky130_fd_sc_hd__clkinv_4 g150(.A (n_9), .Y (n_10));
  sky130_fd_sc_hd__nand2_4 g151(.A (n_3), .B (n_4), .Y (n_9));
  sky130_fd_sc_hd__nand2b_1 g152(.A_N (sel), .B (out[2]), .Y (n_8));
  sky130_fd_sc_hd__nand2b_1 g153(.A_N (out[2]), .B (n_0), .Y (n_7));
  sky130_fd_sc_hd__nand2_2 g154(.A (out[1]), .B (n_1), .Y (n_4));
  sky130_fd_sc_hd__nand2_2 g155(.A (n_2), .B (out[0]), .Y (n_3));
  sky130_fd_sc_hd__nand2_1 g156(.A (sel), .B (n_2), .Y (n_6));
  sky130_fd_sc_hd__inv_2 g157(.A (out[1]), .Y (n_2));
  sky130_fd_sc_hd__inv_2 g158(.A (out[0]), .Y (n_1));
  sky130_fd_sc_hd__clkbuf_1 fopt(.A (out[1]), .X (n_0));
endmodule

module synth_wrapper(clk, rst_n, sel, out);
  input clk, rst_n, sel;
  output [3:0] out;
  wire clk, rst_n, sel;
  wire [3:0] out;
  wire [3:0] counter_out;
  counter u_counter(.clk (clk), .rst_n (rst_n), .sel (sel), .out
       (counter_out));
  sky130_fd_sc_hd__dfrtp_1 \out_reg[2] (.RESET_B (rst_n), .CLK (clk),
       .D (counter_out[2]), .Q (out[2]));
  sky130_fd_sc_hd__dfrtp_1 \out_reg[1] (.RESET_B (rst_n), .CLK (clk),
       .D (counter_out[1]), .Q (out[1]));
  sky130_fd_sc_hd__dfrtp_1 \out_reg[3] (.RESET_B (rst_n), .CLK (clk),
       .D (counter_out[3]), .Q (out[3]));
  sky130_fd_sc_hd__dfrtp_1 \out_reg[0] (.RESET_B (rst_n), .CLK (clk),
       .D (counter_out[0]), .Q (out[0]));
endmodule

